services:
  postgres:
    image: postgres:16-alpine
    container_name: spe4_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projet_spe4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d projet_spe4"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
